"""
Phishing Bank - Catálogo de Flags CTF
"""
FLAGS = {
    "PB{java_gadget_chain_rce}": {"points": 500, "category": "Deserialization", "difficulty": "hard"},
    "PB{php_pop_chain_file_write}": {"points": 500, "category": "Deserialization", "difficulty": "hard"},
    "PB{pickle_rce_via_redis}": {"points": 400, "category": "Deserialization", "difficulty": "medium"},
    "PB{redis_cache_poison_rce}": {"points": 500, "category": "Deserialization", "difficulty": "hard"},
    "PB{svg_xss_ssrf_stored}": {"points": 300, "category": "File Upload", "difficulty": "medium"},
    "PB{zip_slip_path_traversal}": {"points": 400, "category": "File Upload", "difficulty": "medium"},
    "PB{imagemagick_rce_delegate}": {"points": 500, "category": "File Upload", "difficulty": "hard"},
    "PB{pdf_js_ssrf_wkhtmltopdf}": {"points": 400, "category": "File Upload", "difficulty": "medium"},
    "PB{xxe_ofx_file_read}": {"points": 400, "category": "XXE", "difficulty": "medium"},
    "PB{xxe_saml_auth_bypass}": {"points": 500, "category": "XXE", "difficulty": "hard"},
    "PB{xxe_nfe_credential_leak}": {"points": 400, "category": "XXE", "difficulty": "medium"},
    "PB{ssti_jinja2_rce}": {"points": 400, "category": "Injection", "difficulty": "medium"},
    "PB{nosql_injection_auth_bypass}": {"points": 400, "category": "Injection", "difficulty": "medium"},
    "PB{graphql_introspection_data_leak}": {"points": 300, "category": "GraphQL", "difficulty": "easy"},
    "PB{ldap_injection_auth_bypass}": {"points": 400, "category": "Injection", "difficulty": "medium"},
    "PB{jwt_algorithm_confusion_admin}": {"points": 500, "category": "Auth", "difficulty": "hard"},
    "PB{oauth_csrf_account_takeover}": {"points": 500, "category": "Auth", "difficulty": "hard"},
    "PB{2fa_response_manipulation_bypass}": {"points": 400, "category": "Auth", "difficulty": "medium"},
    "PB{race_condition_pix_double_spend}": {"points": 500, "category": "Business Logic", "difficulty": "hard"},
    "PB{idor_uuid_v1_transaction_leak}": {"points": 300, "category": "IDOR", "difficulty": "medium"},
    "PB{mass_assignment_privilege_escalation}": {"points": 400, "category": "API", "difficulty": "medium"},
    "PB{ssrf_aws_metadata_credentials}": {"points": 500, "category": "SSRF", "difficulty": "hard"},
    "PB{blind_ssrf_internal_network_map}": {"points": 500, "category": "SSRF", "difficulty": "hard"},
    "PB{dom_xss_postmessage_session_steal}": {"points": 400, "category": "XSS", "difficulty": "medium"},
    "PB{stored_xss_pix_statement}": {"points": 300, "category": "XSS", "difficulty": "medium"},
    "PB{weak_crypto_aes_ecb_pattern_analysis}": {"points": 400, "category": "Crypto", "difficulty": "medium"},
    "PB{git_exposed_credential_history}": {"points": 300, "category": "Infra", "difficulty": "easy"},
    "PB{debug_endpoint_credential_leak}": {"points": 200, "category": "Infra", "difficulty": "easy"},
    "PB{api_bola_transaction_idor}": {"points": 300, "category": "OWASP API", "difficulty": "medium"},
    "PB{api_key_query_string_log_leak}": {"points": 200, "category": "OWASP API", "difficulty": "easy"},
    "PB{bopla_sensitive_fields_exposed}": {"points": 300, "category": "OWASP API", "difficulty": "medium"},
    "PB{api_rate_limit_sms_bomb_otp_bruteforce}": {"points": 300, "category": "OWASP API", "difficulty": "medium"},
    "PB{api_function_level_auth_admin_access}": {"points": 400, "category": "OWASP API", "difficulty": "medium"},
    "PB{api_ssrf_webhook_aws_imds}": {"points": 500, "category": "OWASP API", "difficulty": "hard"},
    "PB{cors_regex_bypass_credential_theft}": {"points": 400, "category": "OWASP API", "difficulty": "medium"},
    "PB{api_credential_stuffing_no_protection}": {"points": 300, "category": "OWASP API", "difficulty": "medium"},
    "PB{shadow_api_v1_no_auth_transfer}": {"points": 400, "category": "OWASP API", "difficulty": "medium"},
    "PB{unsafe_api_consumption_xss_injection}": {"points": 300, "category": "OWASP API", "difficulty": "medium"},
    "PB{http_verb_tampering_delete_bypass}": {"points": 300, "category": "REST API", "difficulty": "medium"},
    "PB{mass_assignment_patch_kyc_bypass}": {"points": 400, "category": "REST API", "difficulty": "medium"},
    "PB{stack_trace_credential_disclosure}": {"points": 200, "category": "REST API", "difficulty": "easy"},
    "PB{jwt_none_alg_or_weak_secret_forge}": {"points": 400, "category": "REST API", "difficulty": "medium"},
    "PB{api_key_leaked_js_bundle}": {"points": 200, "category": "REST API", "difficulty": "easy"},
    "PB{websocket_idor_realtime_notifications}": {"points": 400, "category": "WebSocket", "difficulty": "medium"},
    "PB{cswsh_session_hijack_transfer}": {"points": 500, "category": "WebSocket", "difficulty": "hard"},
    "PB{idor_content_type_xml_cross_account}": {"points": 400, "category": "API", "difficulty": "medium"},
    "PB{api_version_header_security_bypass}": {"points": 400, "category": "API", "difficulty": "medium"},
}
